### ISSUE TITLE
Move 'Learning Resources' post to 'Learning Resources' page

### ISSUE THREAD

**Issue by JeremyNFT** [LeNPaul/Millennial#31]
Currently the post 2016-05-05-learning-resources.md ('Learning Resources') has a category = facts, which places it on the 'Interesting Facts' page (while the 'Learning Resources' page remains blank).

This seems unintended and that the category should be 'resources'.

**Comment by LeNPaul** [comment]
Thanks! Just made the change, and I'll credit you in the README. Cheers
