### ISSUE TITLE
Issue with how the site is displayed on https.

### ISSUE THREAD

**Issue by kevinolega** [LeNPaul/Millennial#47]
I attempted to install the theme on Github pages and the site shows up differently.
![Screen Shot 2021-04-21 at 8 47 02 AM](https://user-images.githubusercontent.com/8603924/115481107-6fc9b080-a27e-11eb-8ca5-6ce50320bd22.png)

When you click the menu, you're taken to an unsecured http version of the site.

![Screen Shot 2021-04-21 at 8 47 23 AM](https://user-images.githubusercontent.com/8603924/115481112-735d3780-a27e-11eb-8ef2-703dd97c39c1.png)

If you attempt to go to the https version, the formatting seems to break.

![Screen Shot 2021-04-21 at 8 47 02 AM](https://user-images.githubusercontent.com/8603924/115481107-6fc9b080-a27e-11eb-8ca5-6ce50320bd22.png)

My files are hosted here:

https://github.com/kevinolega/philippineislandliving

Please let me know what I need to change.

Thanks.

Kevin.

**Comment by LeNPaul** [comment]
Hi there! Thanks for bringing this up to me. I noticed that you ended up using my Lagrange theme, which seems to work without issue. I just wanted to let you know that I also recently [released a new version](https://github.com/LeNPaul/Millennial/releases/tag/v2.0.0) of Millennial, which may resolve the issue you were originally experiencing, as both Lagrange and Millennial have almost identical heads. Thanks!
